[world]
name = "LS Tournaments V0"
description = "Loot Survivor Tournaments Version 0"
website = "https://github.com/Provable-Games/ls-tournaments"
seed = "ls_tournaments"

[world.socials]
x = "https://x.com/provablegames"
github = "https://github.com/Provable-Games"

[namespace]
default = "ls_tournaments_v0"

[env]
chain_id = "SN_MAINNET"
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
world_address = "0x01b069be8278b3197d8eadd861adcfb57f3572793d1ca155e5f57094de641f0f"
world_block = 1084132

[writers]
"ls_tournaments_v0-Tournament" = ["ls_tournaments_v0-LSTournament"]
"ls_tournaments_v0-TournamentGame" = ["ls_tournaments_v0-LSTournament"]
"ls_tournaments_v0-TournamentEntryAddresses" = ["ls_tournaments_v0-LSTournament"]
"ls_tournaments_v0-TournamentEntriesAddress" = ["ls_tournaments_v0-LSTournament"]
"ls_tournaments_v0-TournamentEntries" = ["ls_tournaments_v0-LSTournament"]
"ls_tournaments_v0-TournamentStartsAddress" = ["ls_tournaments_v0-LSTournament"]
"ls_tournaments_v0-TournamentScores" = ["ls_tournaments_v0-LSTournament"]
"ls_tournaments_v0-TournamentTotals" = ["ls_tournaments_v0-LSTournament"]
"ls_tournaments_v0-TournamentPrize" = ["ls_tournaments_v0-LSTournament"]
"ls_tournaments_v0-Token" = ["ls_tournaments_v0-LSTournament"]
"ls_tournaments_v0-TournamentConfig" = ["ls_tournaments_v0-LSTournament"]

[init_call_args]
"ls_tournaments_v0-LSTournament" = [
    "1", # safe_mode
    "0" # test_mode
]

[migration]
order_inits = []
skip_contracts = [
    "ls_tournaments_v0-tournament_mock", 
    "ls_tournaments_v0-loot_survivor_mock", 
    "ls_tournaments_v0-pragma_mock", 
    "ls_tournaments_v0-eth_mock", 
    "ls_tournaments_v0-lords_mock", 
    "ls_tournaments_v0-erc20_mock", 
    "ls_tournaments_v0-erc721_mock"
]
