[world]
name = "Tournament"
description = "Loot Survivor Tournaments"
website = "https://github.com/Provable-Games/ls-tournaments"
seed = "tournament"

[world.socials]
x = "https://x.com/provablegames"
github = "https://github.com/Provable-Games"

[namespace]
default = "tournament"

[env]
chain_id = "SN_MAINNET"
rpc_url = "https://api.cartridge.gg/x/starknet/mainnet"
world_address = "0x02b127646258e21186e6c7e6234f42583d0d19bf88a57776a404c2cefeb421f2"  # Uncomment and update this line with your world address.

[writers]
"tournament-TournamentModel" = ["tournament-LSTournament"]
"tournament-TournamentGameModel" = ["tournament-LSTournament"]
"tournament-TournamentEntryAddressesModel" = ["tournament-LSTournament"]
"tournament-TournamentEntriesAddressModel" = ["tournament-LSTournament"]
"tournament-TournamentStartIdsModel" = ["tournament-LSTournament"]
"tournament-TournamentEntriesModel" = ["tournament-LSTournament"]
"tournament-TournamentStartsAddressModel" = ["tournament-LSTournament"]
"tournament-TournamentScoresModel" = ["tournament-LSTournament"]
"tournament-TournamentTotalsModel" = ["tournament-LSTournament"]
"tournament-TournamentPrizeKeysModel" = ["tournament-LSTournament"]
"tournament-PrizesModel" = ["tournament-LSTournament"]
"tournament-TokenModel" = ["tournament-LSTournament"]
"tournament-TournamentConfig" = ["tournament-LSTournament"]

[init_call_args]
"tournament-LSTournament" = [
    "1", # safe_mode
    "1" # test_mode
]

[migration]
order_inits = []
skip_contracts = [
    "tournament-tournament_mock", 
    "tournament-loot_survivor_mock", 
    "tournament-pragma_mock", 
    "tournament-eth_mock", 
    "tournament-lords_mock", 
    "tournament-erc20_mock", 
    "tournament-erc721_mock"
]
