world_address = "0x01b069be8278b3197d8eadd861adcfb57f3572793d1ca155e5f57094de641f0f"
rpc = "https://api.cartridge.gg/x/starknet/mainnet"
explorer = false

[indexing]
world_block = 1084132
events_chunk_size = 1024
blocks_chunk_size = 100
transactions = false
contracts = []
namespaces = ["ls_tournaments_v0"]